### ISSUE TITLE
Fetching Uptime from AWS

### ISSUE THREAD

**Issue by abuneri** [Injabie3/discord.injabie3.moe#1]
Make a `GET` request using CURL instead of `file_get_contents` in https://github.com/Injabie3/discord.injabie3.moe/blob/master/uptime/ayumi.php#L2 and https://github.com/Injabie3/discord.injabie3.moe/blob/master/uptime/ren.php#L2, `file_get_contents` is so slow.

**Comment by Injabie3** [comment]
Good point, will do that later 👌

**Comment by Injabie3** [comment]
Hmm, I deployed it on [Heroku](https://ren-bot.herokuapp.com/), and I think the other site is just slow because it's hosted on my computer.  Nonetheless, I'll implement it in the morning.

**Comment by Injabie3** [comment]
@sedruk so something like this?
```php
<?php
    $url = "http://aws.injabie3.moe/uptime/ayumi.php";
    $ch = curl_init( $url );
    curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
    $result = curl_exec($ch);
    curl_close($ch);
    echo $result;
?>
```

**Comment by abuneri** [comment]
👍
