### ISSUE TITLE
Renleaderboard disappears too fast

### ISSUE THREAD

**Issue by dullahan8** [Injabie3/discord.injabie3.moe#7]
I know someone made the request for Ren to remove her renleaderboard output but it disappears too quickly. Can you increase the wait to maybe 30 or 60s?

**Comment by Injabie3** [comment]
Closing, changed to 60 seconds in the following commit: https://github.com/SFUAnime/Ren/commit/90af65b2c72e16c27432e39a3bcffca1e5f5b150
